export const BankLogos: Record<string, any> = {
  "access-bank-diamond": require("@/assets/images/banks/access-bank-diamond.png"),
  "access-bank": require("@/assets/images/banks/access-bank.png"),
  "alat-by-wema": require("@/assets/images/banks/alat-by-wema.png"),
  asosavings: require("@/assets/images/banks/asosavings.png"),
  "cemcs-microfinance-bank": require("@/assets/images/banks/cemcs-microfinance-bank.png"),
  "citibank-nigeria": require("@/assets/images/banks/citibank-nigeria.png"),
  "default-image": require("@/assets/images/banks/default-image.png"),
  "ecobank-nigeria": require("@/assets/images/banks/ecobank-nigeria.png"),
  "ekondo-microfinance-bank": require("@/assets/images/banks/ekondo-microfinance-bank.png"),
  "fidelity-bank": require("@/assets/images/banks/fidelity-bank.png"),
  "first-bank-of-nigeria": require("@/assets/images/banks/first-bank-of-nigeria.png"),
  "first-city-monument-bank": require("@/assets/images/banks/first-city-monument-bank.png"),
  "globus-bank": require("@/assets/images/banks/globus-bank.png"),
  "guaranty-trust-bank": require("@/assets/images/banks/guaranty-trust-bank.png"),
  "heritage-bank": require("@/assets/images/banks/heritage-bank.png"),
  "keystone-bank": require("@/assets/images/banks/keystone-bank.png"),
  "kuda-bank": require("@/assets/images/banks/kuda-bank.png"),
  "lotus-bank": require("@/assets/images/banks/lotus-bank.png"),
  "moniepoint-mfb-ng": require("@/assets/images/banks/moniepoint-mfb-ng.png"),
  paga: require("@/assets/images/banks/paga.png"),
  palmpay: require("@/assets/images/banks/palmpay.png"),
  paycom: require("@/assets/images/banks/paycom.png"), // OPay
  "polaris-bank": require("@/assets/images/banks/polaris-bank.png"),
  "sparkle-microfinance-bank": require("@/assets/images/banks/sparkle-microfinance-bank.png"),
  "stanbic-ibtc-bank": require("@/assets/images/banks/stanbic-ibtc-bank.png"),
  "standard-chartered-bank": require("@/assets/images/banks/standard-chartered-bank.png"),
  "sterling-bank": require("@/assets/images/banks/sterling-bank.png"),
  "taj-bank": require("@/assets/images/banks/taj-bank.png"),
  "union-bank-of-nigeria": require("@/assets/images/banks/union-bank-of-nigeria.png"),
  "united-bank-for-africa": require("@/assets/images/banks/united-bank-for-africa.png"),
  "wema-bank": require("@/assets/images/banks/wema-bank.png"),
  "zenith-bank": require("@/assets/images/banks/zenith-bank.png"),
};
